name: build-kernel
on:
  push:
    branches: 
      - main
    tags:
      - '*'
  workflow_dispatch:
jobs:
  build4:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
      # Step that does that actual cache save and restore
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
        
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
          root-reserve-mb: 8192
          temp-reserve-mb: 2048
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'

    - name: "Setup build environment"
      run: |             
             curl https://raw.githubusercontent.com/akhilnarang/scripts/master/setup/android_build_env.sh | bash -

    - name: "Clone repo, sync"
      run: |
             mkdir out
             repo init -u https://github.com/Yaroslav51-dev/manifest.git -b main --depth=1
             repo sync

    - name: "Build"
      run: |             
             OUT_DIR=out LTO=thin KCFLAGS=-O3 BUILD_CONFIG=common/build.config.msm.liuqin build/build.sh

    - name: Test Report
      uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
          name: out1
          path: /home/runner/work/gki_kernel_build/gki_kernel_build/kernel/out/dist/Image
