name: build-kernel
on:
  push:
    branches: 
      - main
    tags:
      - '*'
  workflow_dispatch:
jobs:
  build-stock:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          temp-reserve-mb: 2048
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          
      - name: "Setup build environmentq"
        run: |             
             curl https://raw.githubusercontent.com/akhilnarang/scripts/master/setup/android_build_env.sh | bash -
             
      - name: "Clone repo, sync"
        run: |
             mkdir $HOMR/kernel && cd $HOME/kernel
             repo init -u https://github.com/Yaroslav51-dev/kernel_manifest-5.10.git -b 14
             repo sync -j$(nproc --all)
             
      - name: "kernel source"
        run: |
             git clone --depth=1 https://github.com/Yaroslav51-dev/android_kernel_xiaomi_liuqin.git -b liuqin-5.10.y $HOME/kernel/common
             
      - name: "build"
        run: |
             cd $HOME/kernel
             LTO=thin BUILD_CONFIG=common/build.config.msm.liuqin build/build.sh
