name: build-kernel
on:
  push:
    branches: 
      - main
    tags:
      - '*'
  workflow_dispatch:
jobs:
  build-stock:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          temp-reserve-mb: 2048
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          
      - name: "Setup build environment"
        run: |             
             curl https://raw.githubusercontent.com/akhilnarang/scripts/master/setup/android_build_env.sh | bash -
             
      - name: "Clone repo, sync, and build"
        run: |
             mkdir kernel && cd kernel
             repo init -u https://android.googlesource.com/kernel/manifest -b common-android12-5.10
             repo sync
             rm -r common
             git clone --depth=1 https://github.com/romiyusnandar/kernel_xiaomi_bengal_515.git -b main common
             cd common
             git fetch https://android.googlesource.com/kernel/common android13-5.15-lts
             git merge FETCH_HEAD
             cd ..
             LTO=thin BUILD_CONFIG=common/build.config.gki.aarch64 build/build.sh
